---
title: "Homework #1"
format:
  html:
    toc: true
    toc-location: left
    theme: vapor
    highlight-style: breeze
    self-contained: true
---

See all that stuff above. You should change `theme` and `highligh-style` to fit your own style. You can find them here: https://quarto.org/docs/output-formats/html-themes.html

Seriously, you should start finding your own style, so definitely change them!

## Data

You'll be working with the following data files:

-   `artist_genre.txt`

-   `artist_name.csv`

-   `artist_net_worth.csv`

-   `artist_number_one_hits.csv`

-   `artist_studio_albums.csv`

-   `artist_top_hits.csv`

The only file that you are going to need to be careful about is the `artist_genre` file -- be sure to look at the extension and refer to the notes!

## Goals

* Read each file and join them together.

* Create variables to capture the following ideas:
    + How long has the artist been around? You can just use their birth year.
    + Something to capture each artist's net worth per studio album.
    + How old was each artist when they had their biggest hit?

* Which artist has been around the longest?

* Which artists are above the mean of net worth per studio album?

* Plot net worth per studio album, the "been around" variable, and genre. There should be points and colors here. 

* Show me something. There is a nice chunk of data here and you've got to have some neat ideas!

* Comment and explain everything!